fix: pydantic defaults must use only built-in datatypes
When mypy complains of a Pydantic field's default value that:

    styletts2\ev_config\__init__.py:340: error: Incompatible types in assignment (expression has type "str", variable has type "Path")  [assignment]

the correct fix is to enable `validate_default`, not cast it. Then the
default will go through the same processing pipeline a value in a config
file would take from its string representation to the Pydantic field,
and it will be cleanly serializable into our schemas.

Path is platform dependant: on Linux and Mac it's serializable by
default with forward slashes, while on Windows it's not serializable and
would use backward slashes even if it was, which we would not want.

For all Pydantic fields of any non built-in type, e.g.
Path, PossiblyRelativePath, Callable, PossiblySerializedCallable, etc,
`validate_default=True` is required and the default should be an str.